export const icons = {
    home: require('../assets/images/homeIcon.png'),
    bag: require('../assets/images/bagIcon.png'),
    store: require('../assets/images/storeIcon.png'),
    profile: require('../assets/images/userIcon.png'),
    whatsapp: require('../assets/images/whatsappIcon.png'),
    map: require('../assets/images/mapIcon.png'),
    bread: require('../assets/icons/Bread.png'),
    pastry: require('../assets/icons/Pastry.png'),
    cake: require('../assets/icons/Cake.png'),
    others: require('../assets/icons/Others.png'),
    location: require('../assets/icons/location.png'),
    bakeBread: require('../assets/images/bakingbread.png'),
    noFile: require('../assets/images/nofile.png'),
    brokenSearch: require('../assets/images/brokensearch.png'),
}